name: release-artifact

on:
  push:
  workflow_dispatch:
    

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > install.sh && chmod 777 install.sh && ./install.sh -y
      - run: cargo build

      - uses: actions/upload-artifact@v7
        with:
          name: gameengine.exe
          path: target/debug/game.exe