name: release-artifact

on:
  push:
  workflow_dispatch:
    

jobs:
  build-project:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - run: winget install -e --id Rustlang.Rustup

      - run: cargo build

      - uses: actions/upload-artifact@v7
        with:
          name: game_engine.exe
          path: target/debug/game.exe

      - run: ls -al
      
      - name: Upload binaries to release
        if: startsWith(github.ref, 'v')
        uses: svenstaro/upload-release-action@v2
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: target/debug/game.exe
            asset_name: game.exe
            tag: ${{ github.ref }}
            overwrite: true
            body: "This is my release text"